nick                = ''
ident               = ''
realname            = ''
server_password     = ''
scan_timeout_hours  = 0
bad_flows           = []
log_channel         = ''
verbose_log_channel = ''
verbose_redirect    = []
oper_key_path       = ''
oper_key_passwd     = ''
oper_name           = ''
ns_user             = ''
ns_passwd           = ''
xline_duration      = 0
xline_message       = ''
[connection]
    Host                  = ''
    Port                  = ''
    TLS                   = false
    InsecureSkipVerifyTLS = false
    TLSCertPath           = ''
    TLSKeyPath            = ''
    RawLog                = false
