nick                = ''
ident               = ''
realname            = ''
server_password     = ''
scan_timeout_hours  = 0    # How long a scan is cached
bad_flows           = []   # OAUTH flows that are deemed not good enough (order and case do not matter)
log_channel         = ''
verbose_log_channel = ''   # secondary loud log channel
verbose_redirect    = []   # Regexp that if matched puts logs in the verbose chan
oper_key_path       = ''
oper_key_passwd     = ''
oper_name           = ''
ns_user             = ''
ns_passwd           = ''
xline_duration      = 0
xline_message       = ''
log_only            = true # Disable Teeth
scan_ranges         = []   # IP ranges that should be checked (as in, connecting users on these IPs)
[connection]
    Host                  = ''
    Port                  = ''
    TLS                   = false
    InsecureSkipVerifyTLS = false
    TLSCertPath           = ''
    TLSKeyPath            = ''
    RawLog                = false
