nick                = ''
ident               = ''
realname            = ''
server_password     = ''
scan_timeout_hours  = 0    # How long a scan is cached
bad_flows           = []   # OAUTH flows that are deemed not good enough (order and case do not matter)
log_channel         = ''
verbose_log_channel = ''   # secondary loud log channel
verbose_redirect    = []   # Regexp that if matched puts logs in the verbose chan
oper_key_path       = ''
oper_key_passwd     = ''
oper_name           = ''
ns_user             = ''
ns_passwd           = ''
log_only            = true # Disable Teeth
scan_ranges         = []   # IP ranges that should be checked (as in, connecting users on these IPs)


# actions contains a list of actions to execute
[actions.name]
    type        = ''   # kline, xline, or warn, the kind of action to take. kline klines EACH user, xline X-Lines the homeserver
    message     = ''   # the message to use in the action's command (for kline and xline this is what you expect), for warn this uses a go template
    duration    = 1440 # the duration for the action, in minutes
    ignore_sasl = true # if true, ignore incoming users if they have used SASL

[connection]
    Host                  = ''
    Port                  = ''
    TLS                   = false
    InsecureSkipVerifyTLS = false
    TLSCertPath           = ''
    TLSKeyPath            = ''
    RawLog                = false
